const GovernmentScheme = require('../models/GovernmentScheme');
const FundingProgram = require('../models/FundingProgram');
const User = require('../models/User');
const UserAssessment = require('../models/UserAssessment');
const BusinessPlan = require('../models/BusinessPlan');
const BusinessIdea = require('../models/BusinessIdea');
const { getRecommendationsForUser } = require('./recommendationEngine');

/**
 * Service to recommend government schemes and funding options to users based on:
 * - State location
 * - Business category / Industry
 * - Assessment / Experience level
 * - Business plan financial estimates
 */

/**
 * Helper to clean and compare states
 */
function stateMatches(userState, schemeState) {
  if (!schemeState || schemeState.toLowerCase() === 'all' || schemeState.toLowerCase() === 'national' || schemeState.toLowerCase() === 'india') {
    return true;
  }
  if (!userState) return false;
  return userState.toLowerCase().trim() === schemeState.toLowerCase().trim();
}

/**
 * Helper to clean and compare industries
 */
function industryMatches(ideaCategory, schemeIndustry) {
  if (!schemeIndustry || schemeIndustry.toLowerCase() === 'all' || schemeIndustry.toLowerCase() === 'multi') {
    return true;
  }
  if (!ideaCategory) return false;
  
  // Custom simple categorization matching (e.g. Fashion -> Tailoring, Retail -> Trading etc)
  const categoryMap = {
    'tailoring & fashion': ['fashion', 'apparel', 'textiles', 'tailoring'],
    'food & catering': ['food', 'catering', 'hospitality', 'beverages'],
    'handicrafts': ['crafts', 'handicrafts', 'art', 'creative'],
    'beauty & wellness': ['beauty', 'wellness', 'healthcare', 'personal care'],
    'repair services': ['repair', 'maintenance', 'electronics', 'mechanic'],
    'agriculture': ['agriculture', 'farming', 'agro', 'rural'],
    'digital services': ['digital', 'technology', 'web', 'software', 'it'],
    'education & training': ['education', 'training', 'coaching'],
    'home services': ['home', 'cleaning', 'interior'],
    'retail & trading': ['retail', 'trading', 'commerce', 'shop']
  };

  const cleanCategory = ideaCategory.toLowerCase().trim();
  const cleanIndustry = schemeIndustry.toLowerCase().trim();

  if (cleanCategory === cleanIndustry) return true;

  const matches = categoryMap[cleanCategory] || [];
  return matches.includes(cleanIndustry) || cleanIndustry.includes(cleanCategory);
}

/**
 * Recommend government schemes for a user
 */
async function recommendSchemesForUser(userId) {
  const user = await User.findById(userId).lean();
  if (!user) throw new Error('User not found');

  const userState = user.profile?.location || '';
  const assessment = await UserAssessment.findOne({ userId }).lean();
  const experienceLevel = assessment?.experienceLevel || 'Beginner';

  // Get recommended business ideas for the user
  const recommendedIdeas = await getRecommendationsForUser(userId);
  const topIdea = recommendedIdeas.length > 0 ? recommendedIdeas[0].businessIdea : null;

  // Fetch all business plans generated by this user
  let activePlans = [];
  if (recommendedIdeas.length > 0) {
    const ideaIds = recommendedIdeas.map(r => r.businessIdea._id);
    activePlans = await BusinessPlan.find({ businessIdeaId: { $in: ideaIds } })
      .populate('costEstimate')
      .populate('revenueProjection')
      .lean();
  }

  const allSchemes = await GovernmentScheme.find({}).lean();

  const recommendations = allSchemes.map(scheme => {
    let score = 50; // Base score
    const matchReasons = [];

    // 1. State matching (40% weight)
    if (scheme.state && scheme.state.toLowerCase() !== 'all') {
      if (userState && stateMatches(userState, scheme.state)) {
        score += 30;
        matchReasons.push(`Specifically tailored for your state: ${scheme.state}.`);
      } else if (userState) {
        // Mismatching state -> deduct score
        score -= 40;
      }
    } else {
      score += 15;
      matchReasons.push('Available nationally across all states.');
    }

    // 2. Industry matching (30% weight)
    if (topIdea) {
      if (industryMatches(topIdea.category, scheme.industry)) {
        score += 20;
        matchReasons.push(`Matches your primary recommended sector: ${topIdea.category}.`);
      }
    }

    // 3. Business Plan startup cost comparison (20% weight)
    const matchingPlan = activePlans.find(plan => {
      // Find plan with matching industry
      const idea = recommendedIdeas.find(r => r.businessIdea._id.toString() === plan.businessIdeaId.toString());
      return idea && industryMatches(idea.businessIdea.category, scheme.industry);
    });

    if (matchingPlan && matchingPlan.costEstimate) {
      const requiredCost = matchingPlan.costEstimate.totalCost;
      if (scheme.fundingAmount >= requiredCost) {
        score += 15;
        matchReasons.push(`Scheme funding (${scheme.fundingAmount}) can fully cover your business plan's estimated startup cost (${requiredCost}).`);
      } else if (scheme.fundingAmount >= requiredCost * 0.5) {
        score += 10;
        matchReasons.push(`Scheme funding covers a significant portion (50%+) of your startup cost.`);
      } else {
        score += 5;
        matchReasons.push(`Scheme provides auxiliary grant support for your startup cost.`);
      }
    }

    // 4. Experience level alignment
    if (experienceLevel === 'Beginner' && (scheme.name.includes('Seed') || scheme.name.includes('MUDRA') || scheme.name.includes('PMEGP'))) {
      score += 10;
      matchReasons.push('Perfect match for early-stage or beginner entrepreneurs.');
    } else if (experienceLevel === 'Experienced' && scheme.name.includes('Guarantee')) {
      score += 10;
      matchReasons.push('Suited for scaling businesses with mature operations.');
    }

    // Normalize score to max 100, min 0
    const finalScore = Math.max(0, Math.min(100, score));

    return {
      scheme,
      matchScore: finalScore,
      reasons: matchReasons.length > 0 ? matchReasons : ['General support scheme for startups.'],
    };
  });

  // Sort by score descending
  recommendations.sort((a, b) => b.matchScore - a.matchScore);
  return recommendations;
}

/**
 * Recommend commercial/bank funding programs for a user
 */
async function recommendFundingForUser(userId) {
  const user = await User.findById(userId).lean();
  if (!user) throw new Error('User not found');

  const assessment = await UserAssessment.findOne({ userId }).lean();
  const experienceLevel = assessment?.experienceLevel || 'Beginner';

  // Get recommended business ideas
  const recommendedIdeas = await getRecommendationsForUser(userId);
  const topIdea = recommendedIdeas.length > 0 ? recommendedIdeas[0].businessIdea : null;

  // Fetch business plans
  let activePlans = [];
  if (recommendedIdeas.length > 0) {
    const ideaIds = recommendedIdeas.map(r => r.businessIdea._id);
    activePlans = await BusinessPlan.find({ businessIdeaId: { $in: ideaIds } })
      .populate('costEstimate')
      .populate('revenueProjection')
      .lean();
  }

  const allFunding = await FundingProgram.find({}).lean();

  const recommendations = allFunding.map(program => {
    let score = 50; // Base score
    const matchReasons = [];

    // 1. Industry matching
    if (topIdea) {
      if (industryMatches(topIdea.category, program.industry)) {
        score += 25;
        matchReasons.push(`Matches your target industry category: ${topIdea.category}.`);
      }
    }

    // 2. Amount and Interest matching
    const matchingPlan = activePlans.find(plan => {
      const idea = recommendedIdeas.find(r => r.businessIdea._id.toString() === plan.businessIdeaId.toString());
      return idea && industryMatches(idea.businessIdea.category, program.industry);
    });

    if (matchingPlan && matchingPlan.costEstimate) {
      const requiredCost = matchingPlan.costEstimate.totalCost;
      if (program.amount >= requiredCost && program.amount <= requiredCost * 2) {
        score += 20;
        matchReasons.push(`Funding limit fits your estimated startup cost structure of ${requiredCost}.`);
      } else if (program.amount < requiredCost) {
        score += 5;
        matchReasons.push(`Provides micro-capital covering a portion of your ${requiredCost} capital requirement.`);
      }
    }

    // Lower interest rate is better
    if (program.interestRate <= 8.0) {
      score += 15;
      matchReasons.push(`Highly attractive interest rate: ${program.interestRate}% p.a.`);
    } else if (program.interestRate <= 10.0) {
      score += 10;
      matchReasons.push(`Standard competitive interest rate: ${program.interestRate}% p.a.`);
    }

    // Experience level alignment
    if (experienceLevel === 'Beginner' && program.name.includes('Rural')) {
      score += 5;
    }

    const finalScore = Math.max(0, Math.min(100, score));

    return {
      program,
      matchScore: finalScore,
      reasons: matchReasons.length > 0 ? matchReasons : ['Standard financial commercial credit program.'],
    };
  });

  recommendations.sort((a, b) => b.matchScore - a.matchScore);
  return recommendations;
}

/**
 * Check eligibility of a specific scheme for a user
 */
async function checkSchemeEligibility(schemeId, userId) {
  const scheme = await GovernmentScheme.findById(schemeId).lean();
  if (!scheme) throw new Error('Scheme not found');

  const user = await User.findById(userId).lean();
  const assessment = await UserAssessment.findOne({ userId }).lean();

  // Find user's active business plans
  const recommendedIdeas = await getRecommendationsForUser(userId);
  const ideaIds = recommendedIdeas.map(r => r.businessIdea._id);
  const businessPlansCount = await BusinessPlan.countDocuments({ businessIdeaId: { $in: ideaIds } });

  const checklist = [];
  let eligibleCount = 0;

  // Criterion 1: Location / State Match
  const isNational = !scheme.state || scheme.state.toLowerCase() === 'all' || scheme.state.toLowerCase() === 'national' || scheme.state.toLowerCase() === 'india';
  const userLocation = user?.profile?.location || '';
  const isStateMatch = isNational || (userLocation && userLocation.toLowerCase().trim() === scheme.state.toLowerCase().trim());
  
  checklist.push({
    criterion: 'State Residency',
    status: isStateMatch ? 'met' : 'unmet',
    message: isNational 
      ? 'Met: Scheme is open nationally to all Indian residents.' 
      : (isStateMatch 
          ? `Met: You reside in ${userLocation}, which matches the target state.`
          : `Unmet: Scheme requires residency in ${scheme.state}. Your profile says: "${userLocation || 'Not specified'}"`),
  });
  if (isStateMatch) eligibleCount++;

  // Criterion 2: Assessment Experience Level Match
  const expLevel = assessment?.experienceLevel || 'Beginner';
  let isExpEligible = true;
  let expMessage = '';
  
  if (scheme.name.includes('Seed') || scheme.name.includes('MUDRA') || scheme.name.includes('PMEGP')) {
    isExpEligible = true; // beginner friendly
    expMessage = `Met: Your assessment level is "${expLevel}", matching the early-stage focus.`;
  } else if (scheme.name.includes('Guarantee')) {
    if (expLevel === 'Beginner') {
      isExpEligible = false;
      expMessage = `Warning: Collateral guarantee schemes typically require established micro-business track record. Your assessment is currently "${expLevel}".`;
    } else {
      expMessage = `Met: Your assessment level is "${expLevel}", suitable for credit guarantees.`;
    }
  } else {
    expMessage = `Met: Open to all entrepreneurial expertise levels.`;
  }

  checklist.push({
    criterion: 'Expertise & Training Level',
    status: isExpEligible ? 'met' : 'warning',
    message: expMessage,
  });
  if (isExpEligible) eligibleCount++;

  // Criterion 3: Business Plan Availability
  const requiresPlan = scheme.name.includes('Seed') || scheme.name.includes('Hackathon');
  const hasPlan = businessPlansCount > 0;
  
  checklist.push({
    criterion: 'Business Plan Integration',
    status: hasPlan ? 'met' : (requiresPlan ? 'unmet' : 'warning'),
    message: hasPlan 
      ? `Met: You have generated ${businessPlansCount} business plan(s) matching your recommended ideas.`
      : (requiresPlan 
          ? 'Unmet: This seed grant program requires a generated business plan for evaluation.'
          : 'Warning: We recommend generating a business plan to apply for credit evaluation.'),
  });
  if (hasPlan || !requiresPlan) eligibleCount++;

  // Criterion 4: Basic Profile Completeness
  const isProfileComplete = user?.name && user?.email && user?.profile?.location && (user?.profile?.skills?.length > 0);
  checklist.push({
    criterion: 'Profile Details',
    status: isProfileComplete ? 'met' : 'warning',
    message: isProfileComplete
      ? 'Met: Your profile details (name, contact location, and skills checklist) are complete.'
      : 'Warning: Please ensure your profile contains valid location, email, and skills list for official verification.',
  });
  if (isProfileComplete) eligibleCount++;

  // Compute final verdict
  const metCount = checklist.filter(c => c.status === 'met').length;
  const isEligible = metCount === checklist.length;

  return {
    schemeId: scheme._id,
    schemeName: scheme.name,
    isEligible,
    eligibleCount: metCount,
    totalCount: checklist.length,
    checklist,
  };
}

module.exports = {
  recommendSchemesForUser,
  recommendFundingForUser,
  checkSchemeEligibility,
};
